"""empty message

Revision ID: 289a7e31c0d9
Revises: 3e10e6adc7c3
Create Date: 2024-08-11 18:53:49.079428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289a7e31c0d9'
down_revision: Union[str, None] = '3e10e6adc7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
