"""Добавление поля количество в таблицы банков

Revision ID: 2a5e3218b0c4
Revises: a92d0c0145d4
Create Date: 2024-08-02 22:56:29.681701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5e3218b0c4'
down_revision: Union[str, None] = 'a92d0c0145d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes_bank', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('spendings_bank', sa.Column('amount', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('spendings_bank', 'amount')
    op.drop_column('incomes_bank', 'amount')
    # ### end Alembic commands ###
