"""Добавление строки текущих накоплений

Revision ID: 42b17e829edb
Revises: 3eb22dc8608a
Create Date: 2024-09-02 20:24:21.463972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b17e829edb'
down_revision: Union[str, None] = '3eb22dc8608a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_saving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('current_savings', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('incomes_bank', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('spendings', 'optional_spending',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('spendings_bank', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spendings_bank', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('spendings', 'optional_spending',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('incomes_bank', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_table('users_saving')
    # ### end Alembic commands ###
