"""empty message

Revision ID: 5b1efe2ef470
Revises: 7a9779f69bd1
Create Date: 2024-08-11 17:56:49.665432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1efe2ef470'
down_revision: Union[str, None] = '7a9779f69bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('incomes_bank_user_fk_fkey', 'incomes_bank', type_='foreignkey')
    op.create_foreign_key(None, 'incomes_bank', 'users', ['user_fk'], ['id'], ondelete='SET NULL')
    op.drop_constraint('spendings_bank_user_fk_fkey', 'spendings_bank', type_='foreignkey')
    op.create_foreign_key(None, 'spendings_bank', 'users', ['user_fk'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spendings_bank', type_='foreignkey')
    op.create_foreign_key('spendings_bank_user_fk_fkey', 'spendings_bank', 'users', ['user_fk'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'incomes_bank', type_='foreignkey')
    op.create_foreign_key('incomes_bank_user_fk_fkey', 'incomes_bank', 'users', ['user_fk'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
