"""Новая миграция

Revision ID: 5beeee0f76da
Revises: 
Create Date: 2024-08-12 19:26:28.897280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5beeee0f76da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_table('incomes',
#    sa.Column('id', sa.Integer(), nullable=False),
#    sa.Column('incomes_name', sa.String(), nullable=True),
#    sa.PrimaryKeyConstraint('id')
#   )
#    op.create_table('spendings',
#    sa.Column('id', sa.Integer(), nullable=False),
#    sa.Column('spending_name', sa.String(), nullable=True),
#    sa.Column('optional_spending', sa.Boolean(), nullable=False),
#    sa.PrimaryKeyConstraint('id')
#    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('users_limit', sa.Numeric(), nullable=True),
    sa.Column('current_balance', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('incomes_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('incomes_fk', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('operation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incomes_fk'], ['incomes.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spendings_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_fk', sa.Integer(), nullable=True),
    sa.Column('spending_fk', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('operation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spending_fk'], ['spendings.id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spendings_bank')
    op.drop_table('incomes_bank')
    op.drop_table('users')
    op.drop_table('spendings')
    op.drop_table('incomes')
    # ### end Alembic commands ###
