version: "3"
services:

  postgres:
    image: postgres:16
    container_name: finance_bot_postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./db.sql:/app/db.sql
    env_file: # Файл с переменными окружения (Вместо environment)
      - .env-db
    restart: always
    
  redis:
    image: redis:7
    container_name: finance_bot_redis
    restart: always
    volumes:
      - redis:/var/lib/redis
    
  main:
    build: .
    container_name: finance_bot
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always
    command: ["/bot/docker_run.sh"]

  adminer:
    image: adminer
    ports:
      - '8888:8080'

volumes:
  data:
  redis:
